### PR TITLE
feat: add British layout, so Defy shows ISO English

### PR DESCRIPTION
**Pull request by javierguzman**

### CODE REVIEW

**Comment by jreklund** [comment]
Hello! Just wanted to let you guys know I'm woring on a re-write of the language select and folder structure to adapt [CLDR v43.0](https://www.unicode.org/cldr/charts/43/supplemental/language_territory_information.html) as I found it quite hard to see what languages already existed (in the code), as some of them where named wrong.

Will probably have the PR up this weekend if you wanna hold off on this one and see the benifits of CLDR v43.0. ENi also dosen't have English (UK) modifiers, so that's something that are getting fixed in that PR as well.

**Comment by javierguzman** [comment]
Hello @jreklund  is that a standard like ISO 639-1?

**Comment by jreklund** [comment]
@javierguzman Something like that, you have en-US (English United States), en-GB (English United Kingdom), sv-SE (Swedish Sweden). It doesn't just take the language en (or sv) into account but territory. There may be a better name for the combination of language code and territory code, 

You can see that standard being used in e.g. web-browser headers:
`Accept-Language: sv,en-US;q=0.9,en;q=0.8`

**Comment by javierguzman** [comment]
> @javierguzman Something like that, you have en-US (English United States), en-GB (English United Kingdom), sv-SE (Swedish Sweden). It doesn't just take the language en (or sv) into account but territory. There may be a better name for the combination of language code and territory code,
> 
> You can see that standard being used in e.g. web-browser headers: `Accept-Language: sv,en-US;q=0.9,en;q=0.8`

Maybe it is because it's Friday night but I do not fully understand. I mean, you are saying we use en-US, en-GB, etc. and there may be a better name (like the standard you mentioned perhaps). Then you specify as an example the web-browser which uses the same naming convention like us, so then we are on the right track, aren't we?

I am not sure I would go for something different than rfc2616/language tags which is what is used by https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n and so on. Is the standard you mentioned meant to replace the ISO one? Just open to learn more.

**Comment by jreklund** [comment]
I'm trying to say that we should use en-US and en-GB instead of referring to them as English and British English. There may be an better name than CLDR v43.0, but that's the list I go by to look them up.

Screenshot 2023-08-25 215656

Currently Sweden are referenced as SW - that's doesn't exists. We have SE for the country Sweden and sv for the language Swedish.

Screenshot 2023-08-25 220659

I have also as you can see started to move away from calling them iso/ansi, as you can use both on the Defy.

**Comment by jreklund** [comment]
@javierguzman I have just finished the code and documentation in question in #492, so it will be easier to see what I mean.

**Comment by javierguzman** [comment]
> I'm trying to say that we should use en-US and en-GB instead of referring to them as English and British English. There may be an better name than CLDR v43.0, but that's the list I go by to look them up.
> 
> 
> Currently Sweden are referenced as SW - that's doesn't exists. We have SE for the country Sweden and sv for the language Swedish.
> 
> 
> I have also as you can see started to move away from calling them iso/ansi, as you can use both on the Defy.

> @javierguzman I have just finished the code and documentation in question in #492, so it will be easier to see what I mean.

Thanks @jreklund! I understand you now. We'll review the PR and let you know our thoughts, right now we have some bugs that has arisen so probably we will merge this one and leave yours for a bit later as this PR is a safe bet if you know what I mean.

Also, I am not a pro about how keyboards work behind the scenes so I will ask to my colleague to check it out. One thing for sure is that even though Defy does not have ISO/ANSI it really needs to have one assigned, the reason is that we have a "normal" keyboard shown for setting the keys up and that keyboard shows ISO/ANSI depending on your language, etc.

**Comment by jreklund** [comment]
No worries @javierguzman! It's a big chunk of changes I made, so take your time to look it over and test it out. :)

**Pull request merged**
