### PR TITLE
Add Polish programmer's layout (klawiatura programisty)

### PR DESCRIPTION
**Pull request by 0rzech**
The other one defined in Polish Standard PN-I-06000:1997 is Polish typist's layout (klawiatura maszynistki). It's not included in this PR.

### CODE REVIEW

**Comment by alexpargon** [comment]
Hey there @0rzech !!

please adapt your language layout to the new language library standard! 👍🏻 

Sorry to make this change but @jreklund had solved the issues for other languages 3 times already after his contribution and was pending merge from august, and I just merged his code to improve the language library. 😅

**Comment by 0rzech** [comment]
Yo, @alexpargon ! 🙂 No problem, I'm on it! 👍🏻

**Comment by 0rzech** [comment]
@alexpargon , done. 🙂

**Comment by alexpargon** [comment]
Great! merging.. 😃

**Pull request merged**
