### PR TITLE
Fix a bunch of typos :)

### PR DESCRIPTION
**Pull request by SamLeatherdale**
Just a few little typos that I spotted.

Would be keen to contribute more substantial changes to the project in the future.

### CODE REVIEW

**Comment by SamLeatherdale** [comment]
@AlexDygma Sorry, not sure how to add reviewers to this PR, I don't think I have access to do so.

**Comment by AlexDygma** [comment]
Hey @SamLeatherdale ! Thanks for the effort! very much appreciated 🤟

**Comment by nbfritz** [comment]
Excellent! @SamLeatherdale -- I came in to create a similar PR, but found this instead!

**Comment by SamLeatherdale** [comment]
Happy to contribute @AlexDygma 

What will it take to get this one over the line?

**Comment by AlexDygma** [comment]
> Happy to contribute @AlexDygma
> 
> What will it take to get this one over the line?

We are here now! a bit late but Defy has been the only focus for a couple of months! now we are preparing for the release so a lot of new features coming up 😄

**Pull request merged**
