### PR TITLE
Defy keyboard flash support

### PR DESCRIPTION
**Pull request by AlexDygma**
This PR adds support to the Bazecor flash tool for Defy keyboards.

- [x] Create Defy keyboard devices
- [x] Add final VID / PID support
- [x] Create custom paths for the flash procedure
- [x] Add the required segmentation to support Defy keyboards as wired and wireless
- [x] Fix the Backup system to support new Defy commands
- [x] Support flashing procedure for Wired version
- [x] Support flashing procedure for Wireless version
- [x] Add sub-modules flashing procedure to update the rest of the boards via streaming

When these modifications are complete, Bazecor will be able to flash both versions of the keyboard independently

### CODE REVIEW

**Comment by Noteolvides** [comment]
https://www.loom.com/share/3cdeec831e5e4bb68664e852e7b5aa8f

**Review by Noteolvides — APPROVED** [review]
Tested :1st_place_medal:

**Comment by AlexDygma** [comment]
@Noteolvides !! please close this PR when you seem it fit 😆

**Review by Noteolvides — APPROVED** [review]
Awesome 😎😎 !

**Pull request merged**
