### PR TITLE
Fix texts for preferences and flash screen, fixed FW to accept 16bit values

### PR DESCRIPTION
**Pull request by AlexDygma**
Fixed quite some bugs introduced in 0.3.2

- improved texts for flashing process
- improved texts for qukeys functions
- fixed firmware function to receive 16 bit values
- made flashing time to recognize bootloader longer to achieve success 100% of times
- activated dark theme color scheme for the color underglow and backlight editor buttons

Signed-off-by: AlexDygma <alex@dygma.com>

### CODE REVIEW

**Comment by GazHank** [comment]
Great work @AlexDygma these updates are coming together really quickly

**Comment by AlexDygma** [comment]
Thanks! I'm pushing ahead a lot of changes because we are starting to work today on the migration to the new interface (aka bazecor 1.0)

we will change material UI for bootstrap so we can make custom fit interfaces that suit better the configuration experience!

**Comment by GazHank** [comment]
Ah cool, I'm glad you mentioned that; I'll stop looking any of the Material UI tweaks or changes I'd considered as it sounds like they will no longer be needed.

Do let me know if there are any aspects I can help with.  Do you still have a trello board where future changes are proposed and prioritised?  (I think I used to have access to one...)  I'd be really keen to help if I can, but am very concious that I dont want to spend time developing something which will be conflicting or made redundant by another inflight change.

Many thanks

Gareth

**Comment by AlexDygma** [comment]
So the trello board was closed because we stopped using trello altogether, so we created one in notion https://www.notion.so/dygma/01cece2fe6464f09ac7ca26552563e9b?v=30616d1fea034aed95dc59fabd1d4856

Hope it helps!

Cheers! Alex

**Pull request merged**
