### PR TITLE
Package cleanup

### PR DESCRIPTION
**Pull request by pabrams**
Upgrade some packages, remove others. See individual commits. 
I created #284 for this PR, but maybe we should leave that open, because the job's not done.
Looks like the linter also did a bunch of stuff; I have to assume those are just changes that were accidentally left out of the last PR.  I could strip those changes out, if appropriate.
Of note:
 - I removed anything referring to jest or wallaby, since we have no tests, at the moment.
 - I removed the firebase stuff, and associated code, which appears dead.
 - popper and jquery are gone now because I swithced to bootstrap-css-only

### CODE REVIEW

**Comment by AlexDygma** [comment]
Hey @pabrams! 

Thanks for this, I'm going to merge your PR to clean and prepare the development branch to start working with tests, as I'm going to add them for bazecor from now on, I'll be working with TDD from now on so we can deliver a "bug-free" version of the app as we possibly can. I wish I did this a year ago when I started working with bazecor, but so much needed to be done that I left it for later xDD totally a bad idea.

**Comment by AlexDygma** [comment]
@pabrams I merged your changes into the development branch to keep adding more things to this beta version before releasing it. do you know how to make it appear as merged in this PR? cause I followed the usual procedure and it's not showing up (just didn't merge it on master, but on development) if not I will close it because it's already done 😄

**Comment by AlexDygma** [comment]
Ah, it seems I squashed your individual commits into a single BIG commit with all the resulting changes of modifying the prettier rules that were inconsistent between the linter and the prettier config file (plus adding the new line length).

**Comment by pabrams** [comment]
Yeah, no worries, if it's done, but not necessarily via merge, you can just close this.

**Comment by AlexDygma** [comment]
Merged by squashing onto development

**Comment by pabrams** [comment]
By the way, I think one of the problems with merging the PR would be the target? I was trying to merge into Dygmalab:master: 
image
but you mentioned you were using a Development branch; we could probably just have changed the target of the PR. We can try that next time.

**Pull request closed without merging**
