### PR TITLE
Upgrade packages

### PR DESCRIPTION
**Pull request by GazHank**
Changes and fixes to allow upgrade to Material-UI 4 and Electron 11

What started out as a few quick fixes for dark mode and to upgrade packages list Electron and Material-UI got a little out of hand.  Given the amount of code changes I'd be happy to break this down into more manageable incremental chucks if that would be helpful.

I have tried to focus on only changing code broken by the package upgrades, but given the upgrade broke parts of the UI, there are some fixes for UI/stying too.

Please note running "yarn rebuild" prior to build may be required due to a known issue with the serialport (https://github.com/serialport/node-serialport/issues/2191)

Signed-off-by: Gareth Hancock gazhank@gmail.com

### CODE REVIEW

**Comment by GazHank** [comment]
It looks like I've more fixes to apply to the theme in the macro editor (hopefully just replicating the changes to Key Selector.

**Comment by AlexDygma** [comment]
Hey @GazHank !

What a huge endeavor you got into! 

It's not working right now as in Mac it isn't able to recognize the keyboard's when they are plugged in, so im not going to merge it for now.

ill try to get into it to fix whatever it's wrong and make it work!

GJ and many thanks for caring so much! ❤️

**Comment by GazHank** [comment]
Hi @AlexDygma,

no problem, it was quite fun (for the most part), although the Serialport build issues were a pain.

Would you mind sharing the error info you are seeing on the mac?

I think it could be due to the serialport build issues, or the workarounds I've added for that.  I have a few ideas we could try but its worth making sure that is where the issue is first.

If we can't quickly debug the mac issue then I'd be happy to break this all down into smaller more manageable changes if that would help?  I think the major breaking changes are really Electron 11, Material-UI and the serialport/usb updates, the rest of the changes are either prework to make those upgrades successful, or post upgrade tidy up.

Many thanks

Gareth

**Comment by AlexDygma** [comment]
I'm going to merge the packages on to a specific local branch to rebase the code to 0.3.1 and add more modifications to that version.

Great job @GazHank ! 💪

**Pull request merged**
