### PR TITLE
Additional Media Controls

### PR DESCRIPTION
**Pull request by GazHank**
Addition of extra media buttons:
- Camera toggle
- Brightness Up
- Brightness Down
- Calculator App

I think this should address https://github.com/Dygmalab/Bazecor/issues/74

### CODE REVIEW

**Comment by GazHank** [comment]
Unfortunately I can't seem to find a working keycode for microphone mic yet :-(

**Comment by AlexDygma** [comment]
Hello Gareth! Thanks for all of your hard work! we haven't been absent but developing the firmware of the raise to implement our next best thing! the superkeys, and 3 more internal projects... 😅

So i didn't have much physical time to interact with all the git issues! you have, as always, done a hell of a job addressing them :) thanks a lot for that!

I'm catching up with the development of the new Bazecor and i will try to release the beta by the end of this week, including the new key configurator! 

before that i will merge all of your changes and make a 'last' release of the current Bazecor before integrating them all on the new version, so that dygmates have the most bug free version of the application while we finish the beta steps.

**Comment by GazHank** [comment]
Hi @AlexDygma that's fab news.  I've been playing with TapDance on my local build and it's quite nice, so am really keen to see how these new features work, I'm sure they will be great.

Can't wait to download the new beta code and take a look :-)

**Comment by ryanerwin** [comment]
Thanks for the idea @GazHank 

Running the latest git checkout, I'm still not seeing the "brightness increase" "brightness decrease" media keys.

image

BTW, would be a nice idea to add the build instructions somewhere to the site...

```
git clone https://github.com/Dygmalab/Bazecor.git && cd Bazecor

yarn

yarn run build:linux # not sure if this is required... probably can be skipped...

yarn start
```

Also, Bazecor doesn't grab the version information from git anywhere, so in the UI you just have the hard coded version number from what I can see...

**Comment by GazHank** [comment]
@ryanerwin git clone https://github.com/Dygmalab/Bazecor.git will have cloned the repository, you will need to download this pull request to see these changes

https://gist.github.com/piscisaureus/3342247 should give the steps you need to download the Pull Request (some of the IDEs like VScode make this nice and easy if you are used to those tools)

**Comment by ryanerwin** [comment]
@GazHank Thank you for the tip on a better way to checkout a PR. That was very helpful.

Bright+, Bright- and Calc are all working great for me.

image

**Pull request merged**
