### PR TITLE
Auto image

### PR DESCRIPTION
**Pull request by pabrams**
Added functionality to automatically save screenshots of each layer when switching to another layer, unless the file config.json does not contain "saveScreenshotOnLayerChange": "true". The config.json can be edited while the application is running, and the setting will take effect on the next layer change.
The screenshots are saved to the same path as the execution path.
I was planning on adding more rich functionality (see #260 ), but this is good enough  for me - someone else can feel free to add frills, or I might add some later if I'm bored.

### CODE REVIEW

**Comment by AlexDygma** [comment]
Wouldn't it be better to add a screenshot button that prints the current layer on demand?

**Comment by pabrams** [comment]
Probably, but I'm not a typical user. I did of course think about doing
that, but I knew I'd find it tedious switching through all layers to click
all the buttons, every time I made some layout changes. I personally prefer
that it happen automatically, and the added delay is almost not even
noticeable, for me.  If you were going to do anything similar in your main
branch, I'd make just one button that somehow grabs screenshots of all
layers.  I'm not sure how difficult that is, but it shouldn't be too bad.
At worst, you just have to re-render all the layouts. Maybe you can do that
without even showing them onscreen.

**Comment by pabrams** [comment]
But if we can re-render at will, maybe it would be better to make that standalone (background) program just render and show whichever layer we wanted on-demand, and skip the part where we save screenshots to disk.

**Comment by AlexDygma** [comment]
> And for that matter, maybe it would be better to tell the standalone (background) program to just render and show whichever layer we wanted on-demand (using hot-keys, of course), skipping the part where we save screenshots to disk.

Hahaha that's a pending project in fact, we want to supercharge that application making it able to change the active layer depending on the application that has the focus on the OS, and also generate a heatmap of key usage to recommend moving the most used modifiers to better ergonomic places.

**Comment by AlexDygma** [comment]
I have closed the old branch as I'm cleaning the repo to better organize future development

**Pull request closed without merging**
