### PR TITLE
Add custom layer names

### PR DESCRIPTION
**Pull request by pabrams**
This is for #249.

Some things I'm not sure about below, which I'm happy to fix (especially if I get a hint):

I've never used yarn before, but I now notice, looking at the diff, that I'm downgrading a bunch of packages.  Anyone know what happened there?  I can't think of what I did that might have caused that.

The changes 1. get saved to .config/Electron/config.json and 2. on **every** change to any layer name. I'm not sure if that's ideal. 

The save changes button gets enabled on the change to layerName, but I don't think it should.  If others agree, I'll figure out how to prevent that.

The actual display of the names could probably stand improvement. Do we want the names in the dropdown values?  Maybe I should have replaced the "Layer 0" stuff instead of concatenating to it?

Do we need to be more clear about how to edit the name? (Just click on it, but maybe that's not obvious)

I just realized I haven't tested this with all settings.  I'm using "only custom layers"...

### CODE REVIEW

**Comment by GazHank** [comment]
It looks like most of the package lock noise might be due to a downgrade of serialport; we really should bump the version back up to ^9 rather than 8

It was only downgraded due to a Linux issue which is now resolved.

**Comment by pabrams** [comment]
I think i might as well add support  for import/export in this pr

**Comment by GazHank** [comment]
Hey @AlexDygma do you think you have the beta version stable enough to start reviewing and accepting PRs again soon?

**Comment by AlexDygma** [comment]
> Hey @AlexDygma do you think you have the beta version stable enough to start reviewing and accepting PRs again soon?

Im on it! the time has arrived :D

**Comment by pabrams** [comment]
Um, careful after merging this; I didn't code or test for the default layers - I only  use custom layers. So better test that, probably.

**Comment by AlexDygma** [comment]
@pabrams I'm probably going to make changes to the interface, so ill test the corner cases.

**Pull request merged**
