### PR TITLE
feat: add listener for crashes

### PR DESCRIPTION
**Pull request by javierguzman**

### CODE REVIEW

**Comment by alexpargon** [comment]
We fixed the bug without resorting to swapping electron's version, so no more need for this testing branch!

**Comment by javierguzman** [comment]
What was the error? Just curiosity now!

**Comment by alexpargon** [comment]
Haha Hi there @javierguzman !

The error was happening in AMD Ryzen CPU's of gen 5XXX due to a USB.getDevices() call that happened at the same time on the main process (NodeJS) and the renderer, once removed from the main caller everything worked 🤪

**Comment by javierguzman** [comment]
Crazy dawg

**Pull request closed without merging**
