### PR TITLE
Fixed Freeze issues in FW and improved flashing process

### PR DESCRIPTION
**Pull request by AlexDygma**
## Added the following changes

- Improved all flashing screens to ease the procedure
- Added new FW that restarts the keyboard when a Freeze occurs

Signed-off-by: AlexDygma <alex@dygma.com>

### CODE REVIEW

**Comment by Acrossfy** [comment]
Please merge and release this ASAP) Can't use my Raise because of freezes ;)

**Comment by Acrossfy** [comment]
> Please merge and release this ASAP) Can't use my Raise because of freezes ;)
Oh, I see you posted a link to this version on the DevBlog. Will check it right now.

**Comment by Acrossfy** [comment]
@AlexDygma sorry for spamming here, but unfortunately I'm one of this 2% who experienced issues with keyboard freezing and also I'm experiencing flashing issues starting from 2.4 (or 2.5).

Before 2.4 (or 2.5) I could flash the Raise without any issues, following recommendations step by step. But with one of these new versions, I started to experience endless flashing or flashing with a full wipe of the layers data.

Usually, I could safely reconnect Raise and re-open Bazecor to see that flashing went successful (the current version is shown in the update menu) and I could upload my layers back.

So now, I had the same endless flashing (neuron blinking blue) and after 10 minutes I decided to disconnect it finally and check the version. When I open Bazecor - I see that the current version is 0.2.7+188, but the keyboard disconnects almost at the same moment (after a few seconds after I pressed CONNECT button in the Bazecor), so now I can't flash my Raise and Load backed up layers from Bazecor anymore.

**Comment by Acrossfy** [comment]
Well... I tried to flash to 2.3 using Bootloader way - the same result - it flashed, but Bazecor disconnects.
Then I tried to reset Neuron (trying to update to 2.7 again) - the same. Never completed. Disconnects after connecting from Bazecor.
Then I changed the cable, then I reinstalled the drivers - the same.
Then I changed the port to USB 3.1 from USB 3.0 and now it does not disconnects.
So now it shows me that I'm on 2.7 and I was able to restore my layers... Happily. Till the next time.

Hope this information helps.

**Comment by AlexDygma** [comment]
Hey there Acrossfy!

Don't worry we are in the progress of releasing this today, but you had a beta all along in reddit! 
https://www.reddit.com/r/DygmaLab/comments/l7pr8l/solving_the_freezing_issue_part_1_turning_freezes/

**Comment by jucor** [comment]
I <3 the simplified flashing procedure! I never remembered to switch to rainbow, having it done automatically is so much smoother, thank you @AlexDygma :)

**Pull request merged**
