### PR TITLE
feat: add Latin American Layout

### PR DESCRIPTION
**Pull request by folivaresrios**
The official [Spanish (Latin American) layout](https://kbdlayout.info/kbdla) is included.

### CODE REVIEW

**Comment by jreklund** [comment]
Hi! Is this the official [Spanish (Latin American)](https://kbdlayout.info/kbdla) or a modified version? If it's the official one it should be named `es-MX` and be placed under `// Official` instead of `// Community`. With the file path `es/MX` (json/ts).

`XX` is reserved for keyboard layouts not installed by default in Windows.
I noticed you named it `es/XX-LATAM`, `es-LATAM`  and `es-LA` in other places.

As this layout is used by e.g.
K'iche' (Guatemala)
Mapudungun (Chile)
Quechua (Bolivia)
Quechua (Ecuador)
Quechua (Peru)
[...]

We should consider using the country ball from Spain (es-ES) instead, as all flags create a miss-match.

Let me know if you need any help!

**Comment by folivaresrios** [comment]
Hi!, Indeed, it is the official version.

The PR is in draft precisely due to several of the points you raise.

Regarding the "java locale," I put a "more generic" one since it covers various locales such as `es-AR`, `es-CL`, `es-PE`, among others.

Regarding the `XX`, I didn't know its specific meaning, so I thought they could be used as a placeholder, and the `community` was used thinking it was developed by the community, my mistake. (I couldn't find documentation about it)

Regarding the flag, I was looking for one that represents Latin America (in the meantime, I left the one from my country), but instead, I will choose the one from Mexico following the `ICU Locale`.

I'll take all your points and apply them now or this weekend.

Best regards, and thanks for the feedback.

**Comment by jreklund** [comment]
This is indeed one of the most problematic keyboard layouts as afaik there aren't a real region of origin and used by some many countries. So your use of `es/XX-LATAM`, `es-XX-latam` would indicate `spanish-all-layout_name`. Where e.g. Bepo, Optimot and Ergol is all based on French, and not a specific dialect, but something created by the community not officially adopted. 

`XX` is just a country code not assign to anywhere, so that's why I re-arranged in such a manner, to easily find the "real ones". I can see the confusion and something that will be made clearer in the future.

My plan is to write a real documentation for how to add keyboard layouts, right now it's just some random notes spread out in multiple files with no clear order. As Dygma is currently re-writing everything in TS I took a break as it looks completely different from then I started to add the instructions.

Thanks for adding it. There have been a couple of requests for it on Dygma's Discord, so will be a nice addition!

**Comment by alexpargon** [comment]
Thanks for the feature @folivaresrios ! and for the dev tips @jreklund  😄 

will review & merge this on RC6 💪🏻

**Pull request merged**
