### PR TITLE
code to launch script that sets udev rules for linux

### PR DESCRIPTION
**Pull request by AlexDygma**
Code to check and install if not present the udev rules for dygma USB devices on linux.

It's not yet tested, so it might fail miserably 😆

Signed-off-by: AlexDygma <alex@dygma.com>

### CODE REVIEW

**Review by nazmulidris — CHANGES_REQUESTED** [review]
@AlexDygma Thanks for creating this PR so quickly.

The script that I had posted in the github issue (https://github.com/Dygmalab/Bazecor/issues/26#issuecomment-808828144) runs in fish shell. I am not sure how many people actually have fish shell installed.

It might be better to use bash syntax instead of fish since all users should have bash installed on their Linux distro.

So this `build/installRules.sh` script basically needs to be converted from fish scripting language to bash.

**Review by nazmulidris — CHANGES_REQUESTED** [review]
Hi @AlexDygma 

I just rewrote my fish script into bash and tested it. Please replace `installRules.sh` file contents with the following:

```bash
#!/usr/bin/env bash

# Run `lsusb` to get the IDs for the currently attached Dygma keyboard.
idstring=$(lsusb | grep Dygma | grep -o 'ID.*:[[:alnum:]]*' | sed 's/ID //')

# Split the string by delimiter ":" to get the two numbers.
ids=(${idstring//:/ })
XXXX=${ids[0]}
YYYY=${ids[1]}
line="SUBSYSTEMS==\"usb\", ATTRS{idVendor}==\"$YYYY\", ATTRS{idProduct}==\"$XXXX\", GROUP="users", MODE=\"0666\""

# Generate the rule file.
echo $line > tempfile
sudo mv tempfile /etc/udev/rules.d/50-dygma.rules

# Reload the `udev` rules.
sudo udevadm control --reload-rules 
```

**Comment by AlexDygma** [comment]
Thanks @nazmulidris !!

ill change it asap :)

**Comment by nazmulidris** [comment]
Thanks @AlexDygma - that is awesome! :tada: :clap: 
And you are most welcome - I am glad I could help out :pray:

**Pull request merged**
