### PR TITLE
feat: Extend ClearLayer

### PR DESCRIPTION
**Pull request by folivaresrios**
It is an improvement that allows selecting the entire keyboard or any of its sides to apply the layer cleaning.

clearlayer

It will remain in draft, as if I get a bit more motivated, I will apply these improvements to the color application.
Any suggestions or corrections are welcome.

### CODE REVIEW

**Comment by folivaresrios** [comment]
Add:

Fix visual bug:
When opening the layer cleaning dialog, the default color selection and the 'no change' option are displayed because the component used (Dialog) has autofocus on the button. This was modified by a styled component to avoid it, as it does not have an 'initialFocus' in its API.

before:
CleanShot 2024-07-06 at 17 55 23

after:
CleanShot 2024-07-06 at 17 56 42

**Comment by folivaresrios** [comment]
Do this, but in a different branch, what do you think?
propuesta

**Comment by alexpargon** [comment]
Hey there @folivaresrios!

Seems like a very nice addition! i will review the changes and test it on my side!

**Comment by folivaresrios** [comment]
> Hey there @folivaresrios!
> 
> Seems like a very nice addition! i will review the changes and test it on my side!

Hey @alexpargon 

When you have time, you can review this pull request #825. I Apply the same logic but in the color bar

**Pull request merged**
