### PR TITLE
chore: add package-lock.json to source control

### PR DESCRIPTION
**Pull request by pabrams**

### CODE REVIEW

**Comment by pabrams** [comment]
Why was this closed?

**Comment by HybridEidolon** [comment]
@AlexDygma why was this merged? this project uses yarn's lockfile, not npm's, doesn't it?

**Comment by pabrams** [comment]
It was probably merged because I asked why it wasn't merged...  I'd forgotten that it wasn't used.

**Comment by AlexDygma** [comment]
Basically, i thought you were more used with npm than with yarn, and as you insisted, I supposed other users might want the same as you, that is to use npm in favor of yarn, but I had to remove it now as GitHub actions were taking the package-lock file instead of the yarn.lock file xDD so now I deleted it again.

**Comment by pabrams** [comment]
nah I just had an idiot moment

**Pull request merged**
